### ISSUE TITLE
the code execution step

### ISSUE THREAD

**Issue by ayoubOUSSM2021** [hblyp/pcsrt#1]
Hello,
I have been trying to run this code, but I keep encountering errors at the last step. Here's how I wrote the code, and I was wondering if you could help me identify where my mistake is: 

target/release/pcsrt [OPTIONS] --centroid [LAT(float)],[LON(float)],ELEVATION[(float)] --time-range FROM [(2020-01-01T12:00:00.000Z),TO(2020-03-23T18:00:00.000Z)] --step-mins [int] --linke-turbidity-factor [SINGLE_LINKE(float)]  [INPUT_FILE] [OUTPUT_FILE]

I would be very grateful if you could assist me. Thank you in advance.

**Comment by hblyp** [comment]
Hi,
replace the [PLACEHOLDER]s with values you need, e.g. `./target/release/pcsrt --centroid 57.362845,12.976645,225 --time-range 2020-01-01T12:00:00.000Z,2020-03-23T18:00:00.000Z --step-mins 60 --linke-turbidity-factor 3.5 ./input.las ./output.las`.

**Comment by ayoubOUSSM2021** [comment]
Hello, thank you very much for your response. I have obtained the results, but I am encountering an error while constructing the normals (please refer to the yellow-highlighted line in the attached screenshot). Additionally, my point cloud includes the attributes X Y Z R G B. Could you please let me know the possible source of this error? Thank you very much for your assistance.
![screen](https://user-images.githubusercontent.com/87376316/230091383-ebf390b5-bcbe-4d9c-a6aa-9bcf6ba24d93.JPG)

**Comment by hblyp** [comment]
It's just a warning. Normal vectors are usually not constructed in voxels that do not have sufficient points within their volume or volume of adjacent voxels. In that case a vertical normal vector (`[0;0;1]`) is used instead and the voxel is treated as horizontal plane when calculating the incidence angle of the solar rays.

**Comment by ayoubOUSSM2021** [comment]
thanks a lot for your help
